### ISSUE TITLE
Understand external links syntax from scaladoc

### ISSUE THREAD

**Issue by ktoso** [typesafehub/genjavadoc#51] opened 2015-05-18 18:35 UTC
As seen in: https://github.com/akka/akka/pull/17386/files#diff-86b129a2f383901f6ab2cfd307258525R25
genjavadoc does not currently understand external links syntax.

**Comment by rkuhn** [comment] 2015-06-26 09:05
duplicate of #43

**Closed by rkuhn** 2015-06-26 09:05 UTC
Labels: enhancement
